import type { Metadata } from "next";
import "./globals.css";

import { Sofia_Sans } from "next/font/google";

const sofiaSans = Sofia_Sans({
  subsets: ["latin"],
  variable: "--font-sofia",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sofiaSans.variable} min-h-screen bg-background antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
